feign:
  client:
    config:
      default: # 모든 feign client에 적용
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        defaultRequestHeaders:
          Custom-Header: "global-header-value"
          Accept: "application/json"
spring:
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000
        ok-http:
          read-timeout: 5000