server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: localmaster
    password: qwer1234

  jpa:
    database: postgresql
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update # or create, update, create-drop, validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true


