keycloak:
  auth-server-url: http://localhost:9001
  realm: dev-realm
  resource: spring-boot-app
  redirect-url: http://localhost:8080/api/v1/keycloak/callback
  credentials:
    secret: WQpTOpHkWwuTsvaiCwVVrs8vMvKLNom0



spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full      # 전체 모두 기록
            defaultRequestHeaders:

            retryer:
              period: 100  # 초기 재시도 간격 (밀리초)
              maxPeriod: 1000  # 최대 재시도 간격 (밀리초)
              maxAttempts: 3  # 최대 재시도 횟수
          keycloak-auth-client:
            logger-level: none      # 기록하지 않음





