keycloak:
  auth-server-url: http://localhost:9001
  realm: dev-realm
  resource: spring-boot-app
  redirect-url: http://localhost:8080/api/v1/keycloak/callback
  credentials:
    #    secret: WnmQEGAOzEJ7Kyr2UCJha5AXKCjwnGpB
    # HOME
    secret: WQpTOpHkWwuTsvaiCwVVrs8vMvKLNom0

