spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-boot-app
            client-secret: WQpTOpHkWwuTsvaiCwVVrs8vMvKLNom0
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/your-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/realms/your-realm/protocol/openid-connect/auth
            user-info-uri: http://localhost:8080/realms/your-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/realms/your-realm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:9001
  realm: dev-realm
  client-id: spring-boot-app
  client-secret: z4q0ONegiuXAt4lMCUwFUqh27172DYnf
  url:
    get-token-url: /protocol/openid-connect/token


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    com.blog.springbootkeycloak: BEBUG
    root: DEBUG

